services:
  portfolio:
    build: .
    container_name: portfolio_container
    ports:
      - "8001:80"
    env_file:
      - .env
    environment:
      - ERP_API_URL=http://host.docker.internal:8004
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped